### ISSUE TITLE
2.3.0 upgrade causes conditional assignment to fail

### ISSUE THREAD

**Issue by TechRsch** [kenn/redis-classy#4]
I have been running 2.2.0 successfully.  When I updated with Bundler, it installed 2.3.0.  At that point, my conditional assignment fails with the message: 

> Uncaught exception: RedisClassy.redis must be assigned first.

Falling back to 2.2.0 resolves this issue.  Also, making the assignment unconditional works.  The assignment is:

`RedisClassy.redis ||= Redis.new(host: @redis_uri.host, port: @redis_uri.port, password: @redis_uri.password)`

I also noted that checking RedisClassy.redis for nil also fails with that message.  Is this expected behavior?

**Comment by kenn** [comment]
My bad! Just fixed this behavior in v2.3.1 - please check if it works for you!
